/*
 * include/jnu/fbcon.h — Framebuffer text console.
 *
 * Consumes Limine's framebuffer response. Renders a built-in 8x16
 * monospace font (generated by scripts/gen-font.py). Registers as a
 * klog backend on success.
 *
 * Copyright (c) 2026 The JNU Authors.
 * SPDX-License-Identifier: GPL-2.0-only
 */

#pragma once

#include <jnu/types.h>

struct fbcon_info {
	void *addr;	 /* HHDM-mapped framebuffer base */
	uint64_t width;	 /* pixels */
	uint64_t height; /* pixels */
	uint64_t pitch;	 /* bytes per scanline */
	uint16_t bpp;	 /* bits per pixel; 32 expected */
};

/*
 * Initialize the framebuffer console. Returns 0 on success or a
 * negative errno on failure (no framebuffer, unsupported bpp).
 *
 * On success, registers a klog backend named "fbcon".
 */
int fbcon_init(const struct fbcon_info *fb);

/* Direct write path used by panic to bypass the ring buffer. */
void fbcon_write(const char *buf, size_t len);
