#!/usr/bin/env bash
# scripts/gen-uapi.sh — Generate user/libjnu/include/jnu_syscall.h from UAPI.
#
# Usage: gen-uapi.sh <out.h>
#
# Copyright (c) 2026 The JNU Authors.
# SPDX-License-Identifier: GPL-2.0-only

set -euo pipefail

if [ "$#" -ne 1 ]; then
	echo "usage: gen-uapi.sh <out.h>" >&2
	exit 2
fi

out="$1"
root="$(cd "$(dirname "$0")/.." && pwd)"
nr="$root/include/uapi/jnu/syscall_nr.h"
stat="$root/include/uapi/jnu/stat.h"

if [ ! -f "$nr" ]; then
	echo "gen-uapi.sh: missing $nr" >&2
	exit 1
fi

mkdir -p "$(dirname "$out")"

{
	cat <<'HDR'
/*
 * AUTO-GENERATED by scripts/gen-uapi.sh — do not edit by hand.
 *
 * v0.0.3 §2.2: Linux x86_64-compatible syscall numbers from
 * include/uapi/jnu/syscall_nr.h.
 *
 * SPDX-License-Identifier: GPL-2.0-only
 */

#pragma once

typedef unsigned long size_t;
typedef signed long ssize_t;
typedef signed long int64_t;
typedef unsigned long uint64_t;
typedef unsigned int uint32_t;

HDR

	# Emit JNU_SYS_* defines from syscall_nr.h (skip comments and JNU_SYS_MAX).
	grep -E '^#define JNU_SYS_' "$nr" | grep -v 'JNU_SYS_MAX'

	cat <<'MID'

#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2

MID

	# struct jnu_stat from uapi stat.h (strip include guards and stdint).
	awk '/^struct jnu_stat/,/^};/' "$stat"

	cat <<'TAIL'

long jnu_syscall0(long nr);
long jnu_syscall1(long nr, long a0);
long jnu_syscall2(long nr, long a0, long a1);
long jnu_syscall3(long nr, long a0, long a1, long a2);
long jnu_syscall4(long nr, long a0, long a1, long a2, long a3);

int close(int fd);
int execve(const char *path, char *const argv[], char *const envp[]);
void exit(int status) __attribute__((noreturn));
int fstat(int fd, void *st);
int fork(void);
int getpid(void);
int64_t lseek(int fd, int64_t off, int whence);
int open(const char *path, int flags);
ssize_t read(int fd, void *buf, size_t len);
int waitpid(int pid, int *status);
ssize_t write(int fd, const void *buf, size_t len);
int yield(void);
TAIL
} >"$out"

echo "gen-uapi.sh: wrote $out"
