#!/usr/bin/env bash
#
# scripts/gen-symbols.sh — emit a sorted symbol table from a linked kernel ELF.
#
# Usage: gen-symbols.sh kernel.elf > symbols_data.c
#
# Pulls FUNC and OBJECT symbols whose address is in the kernel-image range
# (>= 0xFFFFFFFF80000000), sorts them, and writes a C array compatible
# with `kernel/kernel/symbols.c`. We only emit FUNC symbols by default
# because backtrace lookups are RIP-keyed.
#
# Copyright (c) 2026 The JNU Authors.
# SPDX-License-Identifier: GPL-2.0-only

set -euo pipefail

if [ $# -lt 1 ]; then
	echo "usage: $0 kernel.elf" >&2
	exit 2
fi

ELF="$1"
NM="${NM:-nm}"

cat <<'HDR'
/*
 * AUTO-GENERATED by scripts/gen-symbols.sh — do not edit by hand.
 *
 * SPDX-License-Identifier: GPL-2.0-only
 */

#include <jnu/symbols.h>
#include <jnu/types.h>

const struct ksymbol jnu_symbols[] = {
HDR

"$NM" -n --defined-only "$ELF" \
	| awk '$2 ~ /[tTwW]/ && $1 ~ /^ffffffff[89a-f]/ { printf("\t{ 0x%s, \"%s\" },\n", $1, $3) }'

cat <<'TAIL'
	{ 0, "" }
};

const size_t jnu_symbols_count =
	sizeof(jnu_symbols) / sizeof(jnu_symbols[0]) - 1;

bool symbols_lookup(uint64_t addr, const char **name, uint64_t *offset)
{
	if (jnu_symbols_count == 0) {
		return false;
	}
	size_t lo = 0, hi = jnu_symbols_count;
	while (lo + 1 < hi) {
		size_t mid = (lo + hi) / 2;
		if (jnu_symbols[mid].addr <= addr) {
			lo = mid;
		} else {
			hi = mid;
		}
	}
	if (jnu_symbols[lo].addr > addr) {
		return false;
	}
	*name   = jnu_symbols[lo].name;
	*offset = addr - jnu_symbols[lo].addr;
	return true;
}
TAIL
