#!/usr/bin/env bash
# scripts/gen-buildinfo.sh — emit build/obj/buildinfo.c.
#
# Reads VERSION, SHA, BUILDTIME from the environment. Output is a
# single C file with three string symbols printed by kernel_main on
# every boot.
#
# Copyright (c) 2026 The JNU Authors.
# SPDX-License-Identifier: GPL-2.0-only

set -euo pipefail

if [ "$#" -ne 1 ]; then
	echo "usage: gen-buildinfo.sh <out-c-file>" >&2
	exit 2
fi

out="$1"
mkdir -p "$(dirname "$out")"

: "${VERSION:=0.0.3.1}"
: "${SHA:=unknown}"
: "${BUILDTIME:=unknown}"

cat > "$out" <<EOF
/*
 * buildinfo.c — generated by scripts/gen-buildinfo.sh.
 *
 * Do not edit; regenerated on every build.
 *
 * SPDX-License-Identifier: GPL-2.0-only
 */

const char jnu_version[]   = "$VERSION";
const char jnu_build[]     = "$SHA";
const char jnu_buildtime[] = "$BUILDTIME";
EOF
