/*
 * kernel/kernel/symbols.c — Stub symbol table.
 *
 * The real table is generated by `scripts/gen-symbols.sh` from the
 * linked kernel ELF and copied over this file before the *final* link
 * (the build does a two-pass link: pass 1 produces an ELF whose symbol
 * names we extract, pass 2 includes those names baked in as a sorted
 * `{addr, name}[]`). The lookup function is the same in both passes;
 * only the table changes.
 *
 * This stub is what the first-pass link sees: an empty table that
 * makes `symbols_lookup` always miss. Backtraces in the first-pass
 * binary therefore print "(?)" instead of names — that ELF is only
 * the input to nm, so it is never run.
 *
 * Copyright (c) 2026 The JNU Authors.
 * SPDX-License-Identifier: GPL-2.0-only
 */

#include <jnu/symbols.h>
#include <jnu/types.h>

const struct ksymbol jnu_symbols[] = {
	{ 0, "" }
};

const size_t jnu_symbols_count = 0;

bool symbols_lookup(uint64_t addr, const char **name, uint64_t *offset)
{
	if (jnu_symbols_count == 0) {
		return false;
	}

	size_t lo = 0, hi = jnu_symbols_count;
	while (lo + 1 < hi) {
		size_t mid = (lo + hi) / 2;
		if (jnu_symbols[mid].addr <= addr) {
			lo = mid;
		} else {
			hi = mid;
		}
	}

	if (jnu_symbols[lo].addr > addr) {
		return false;
	}

	*name = jnu_symbols[lo].name;
	*offset = addr - jnu_symbols[lo].addr;
	return true;
}
